spring:
  application:
    name: notion-api
  datasource:
    url: ${POSTGRESQL_URL:jdbc:postgresql://localhost:5432/cp_db}
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

notion:
  version: 2026-03-11
  base-url: https://api.notion.com
  client-id: ${NOTION_CLIENT_ID}
  client-secret: ${NOTION_CLIENT_SECRET}
  auth-url: https://api.notion.com/v1/oauth/authorize
  token-url: /v1/oauth/token
  redirect-uri: http://localhost:8080/notion/oauth/callback

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: http://localhost:8080/google/oauth/callback
  auth-uri: https://accounts.google.com/o/oauth2/v2/auth
  token-url: https://oauth2.googleapis.com/token

gmail:
  gmail-api-base-url: https://gmail.googleapis.com
