### 변수 정의
@email = goochul175465@gmail.com
@messageId = 19e303113b8daa0f

### 메시지 목록 가져오기
GET localhost:8080/gmail/messages?email={{email}}

### 메시지 상세 가져오기
GET localhost:8080/gmail/message/{{email}}?messageId={{messageId}}
